name: lakasir
recipe: laravel
proxxy:
  web:
    - lakasir.lndo.site
  web2:
    - admin.lakasir.lndo.site
services:
  appserver:
    xdebug: false
  database:
    portforward: 3305
config:
  via: nginx
  php: '8.2'
  webroot: public
  composer_version: '2.2.12'
  database: mysql
