# nixpacks.toml

# Configura las variables de entorno que Nixpacks usará durante la compilación.
[variables]
APP_KEY = "" # Debes establecer esta variable en la configuración de tu servicio.
NIXPACKS_PHP_ROOT_DIR = "/app/public"

# Define las fases del proceso de construcción.
[phases]

# Fase 'setup': instala las dependencias del sistema.
[phases.setup]
nixpkgsArchive = "nixos-23.11"
nixPkgs = [
    # Se especifica PHP 8.1 con las extensiones necesarias, incluyendo pdo_mysql.
    "(php81.withExtensions (pe: with pe; [ fpm pdo pdo_mysql gd curl mbstring zip fileinfo intl exif bcmath sodium]))",
    "php81Packages.composer",
    "nginx",
    "nodejs_20",
    "yarn-1_x"
]

# Fase 'install': instala las dependencias de la aplicación SIN ejecutar scripts.
[phases.install]
cmds = [
    "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --no-scripts", # <-- Se añadió --no-scripts
    "yarn install",
]

# Fase 'build': ÚNICAMENTE compila los assets.
[phases.build]
cmds = [
    "yarn run build" # <-- Se eliminaron todos los comandos 'php artisan'
]

# Configuración del comando de inicio de la aplicación.
[start]
cmd = "php-fpm & nginx -g 'daemon off;'"
