# nixpacks.toml

# Configura las variables de entorno que Nixpacks usará durante la compilación.
[variables]
APP_KEY = "" # Debes establecer esta variable en la configuración de tu servicio.
NIXPACKS_PHP_ROOT_DIR = "/app/public"

# Define las fases del proceso de construcción.
[phases]

# Fase 'setup': instala las dependencias del sistema.
[phases.setup]
# Utiliza el archivo de NixOS 23.11 para los paquetes.
nixpkgsArchive = "nixos-23.11"
# Lista de paquetes de Nix necesarios para la aplicación.
nixPkgs = [
    # Se especifica PHP 8.1 con un conjunto de extensiones comunes para Laravel.
    "(php81.withExtensions (pe: with pe; [ fpm pdo pdo_mysql gd curl mbstring zip fileinfo intl exif bcmath sodium]))",
    "php81Packages.composer", # Instala Composer.
    "nginx",                  # Servidor web Nginx.
    "nodejs_20",              # Instala Node.js versión 20.
    "yarn-1_x"                # Instala Yarn.
]

# Fase 'install': instala las dependencias de la aplicación.
[phases.install]
cmds = [
    "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader", # Instala dependencias de PHP para producción.
    "yarn install", # Instala dependencias de JavaScript/Node.js.
]

# Fase 'build': compila los assets y prepara la aplicación.
[phases.build]
cmds = [
    "yarn run build", # Compila los assets del frontend (Vite, etc.).
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan config:cache",
    "php artisan view:cache"
]

# Configuración del comando de inicio de la aplicación.
[start]
cmd = "php-fpm & nginx -g 'daemon off;'"
