services: 
  lakasir: 
    image: lakasir:dev
    container_name: lakasir
    cpus: 0.25
    mem_limit: 512M
    privileged: true
    ports:
      - 127.0.0.1:8000:80
    volumes:
      # laravel & frontend
      - ../../app:/apps/app
      - ../../config:/apps/config
      - ../../database:/apps/database
      - ../../lang:/apps/lang
      - ../../resource:/apps/resource
      - ../../routes:/apps/routes
      - ../../public:/apps/public
      - ../../storage/app:/apps/storage/app
      - ../../storage/logs:/apps/storage/logs
      - ../../composer.json:/apps/composer.json
      - ../../composer.lock:/apps/composer.lock
      - ../../package.json:/apps/package.json
      - ../../package-lock.json:/apps/package-lock.json
      - ../../vite.config.js:/apps/vite.config.js
      - ../../tailwind.config.js:/apps/tailwind.config.js
      - ../../postcss.config.js:/apps/postcss.config.js
      - ../../yarn.lock:/apps/yarn.lock

      # infrastructure
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/http.d/:/etc/nginx/http.d/
    networks:
      - lakasir
    
  database:
    image: mariadb:10.11.5
    container_name: database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ../../storage/app/mysql:/var/lib/mysql:rw
      - ../../storage/logs:/var/log/mysql:rw
    cpus: 0.25
    mem_limit: 512M
    ports:
      - 3306:3306
    networks:
      - lakasir

networks:
  lakasir:
    external: true
    name: services